apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: channamma/happyapp:v1.0
        ports:
        - containerPort: 80
        env:
        - name: KUBERNETES_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
